apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: clowder
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/hcc-devprod-tenant/clowder/clowder@sha256:69502fb4327116db74b75d5cfee058a87913d468c32816d0094dea0cac4520f3
        name: container-image
        resources: {}
status: {}
