apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: clowder
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clowder
    app.kubernetes.io/part-of: clowder
  name: clowder
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: clowder
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: clowder
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/hcc-devprod-tenant/clowder/clowder@sha256:69502fb4327116db74b75d5cfee058a87913d468c32816d0094dea0cac4520f3
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
