apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: clowder
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clowder
    app.kubernetes.io/part-of: clowder
  name: clowder
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app.kubernetes.io/instance: clowder
status:
  loadBalancer: {}
